# Generated by Django 3.0.2 on 2020-01-31 07:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('client_register_email', 'Подтверждение электронной почты при регистрации'), ('client_register_sms', 'Подтверждение телефона при регистрации'), ('client_forgot_password_email', 'Восстановление пароля по электронной почте'), ('client_forgot_password_sms', 'Восстановление пароля по телефону')], max_length=100, unique=True, verbose_name='Шаблон уведомления')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
                ('is_notification_sms', models.BooleanField(default=True, verbose_name='Уведомления по SMS')),
                ('is_notification_email', models.BooleanField(default=True, verbose_name='Уведомления по Электронной почте')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'шаблон',
                'verbose_name_plural': 'шаблоны',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.Template', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ['-created'],
            },
        ),
    ]
