# Generated by Django 3.0.2 on 2020-01-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(choices=[('client_register_email', 'Подтверждение электронной почты при регистрации'), ('client_register_sms', 'Подтверждение телефона при регистрации'), ('client_forgot_password_email', 'Восстановление пароля по электронной почте'), ('client_forgot_password_sms', 'Восстановление пароля по телефону'), ('client_invoice_email', 'Сформирован новый счет')], max_length=100, unique=True, verbose_name='Шаблон уведомления'),
        ),
    ]
