# Generated by Django 3.0.2 on 2020-02-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200131_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Id Сообщения'),
        ),
    ]
