# Generated by Django 3.0.2 on 2020-02-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_email', models.EmailField(blank=True, max_length=200, verbose_name='Электронная почта для тестирования')),
                ('test_phone', models.CharField(max_length=50, verbose_name='Телефон для тестирования')),
            ],
            options={
                'verbose_name': 'настройки',
                'verbose_name_plural': 'настройки',
            },
        ),
    ]
