# Generated by Django 3.0.2 on 2020-02-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='test_email',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='test_phone',
        ),
        migrations.AddField(
            model_name='preference',
            name='email',
            field=models.EmailField(default=1, max_length=200, verbose_name='Электронная почта отправителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='phone',
            field=models.CharField(default=1, max_length=50, verbose_name='Телефон отправителя'),
            preserve_default=False,
        ),
    ]
