# Generated by Django 3.0.2 on 2020-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200201_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='test_email',
            field=models.EmailField(default=1, max_length=200, verbose_name='Тестовая электронная почта получателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='test_phone',
            field=models.CharField(default=1, max_length=50, verbose_name='Тестовый телефон получателя'),
            preserve_default=False,
        ),
    ]
