# Generated by Django 3.0.2 on 2020-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200201_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, max_length=250, verbose_name='Ссылка'),
        ),
    ]
