# Generated by Django 3.0.2 on 2020-02-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200201_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='is_notification_email',
            field=models.BooleanField(default=False, verbose_name='Уведомления по Электронной почте'),
        ),
        migrations.AlterField(
            model_name='template',
            name='is_notification_sms',
            field=models.BooleanField(default=False, verbose_name='Уведомления по SMS'),
        ),
    ]
