# Generated by Django 3.0.2 on 2020-02-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200201_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.Template', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(choices=[('client_registration_email', 'Подтверждение электронной почты при регистрации'), ('client_registration_sms', 'Подтверждение телефона при регистрации'), ('client_forgot_password_email', 'Восстановление забытого пароля по электронной почте'), ('client_forgot_password_sms', 'Восстановление пароля по телефону'), ('client_invoice_email', 'Сформирован новый счет')], max_length=100, unique=True, verbose_name='Шаблон уведомления'),
        ),
    ]
